name: Claude Code Assistant with Auto Token Refresh

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  workflow_dispatch:  # Allows manual triggering
  schedule:
    # Refresh token every 6 hours to prevent expiration
    - cron: '0 */6 * * *'

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  refresh-and-run-claude:
    # Only run if comment contains @claude or if it's a scheduled/manual run
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      github.event_name == 'schedule' ||
      github.event_name == 'workflow_dispatch'
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Refresh Claude OAuth Token
        id: refresh_token
        env:
          CLAUDE_REFRESH_TOKEN: ${{ secrets.CLAUDE_REFRESH_TOKEN }}
        run: |
          python - << 'EOF'
          import os
          import json
          import urllib.request
          import urllib.error
          
          def refresh_token(refresh_token):
              url = "https://console.anthropic.com/v1/oauth/token"
              data = json.dumps({
                  "grant_type": "refresh_token",
                  "refresh_token": refresh_token
              }).encode('utf-8')
              
              req = urllib.request.Request(url, data=data)
              req.add_header('Content-Type', 'application/json')
              
              try:
                  with urllib.request.urlopen(req) as response:
                      result = json.loads(response.read().decode('utf-8'))
                      return result
              except urllib.error.HTTPError as e:
                  error_body = e.read().decode('utf-8')
                  raise Exception(f"HTTP {e.code}: {error_body}")
          
          # Get refresh token from environment
          refresh_token_value = os.environ.get("CLAUDE_REFRESH_TOKEN")
          if not refresh_token_value:
              raise Exception("CLAUDE_REFRESH_TOKEN not found in secrets")
          
          print("🔄 Refreshing Claude OAuth token...")
          
          try:
              # Refresh the token
              token_response = refresh_token(refresh_token_value)
              
              if "access_token" not in token_response:
                  raise Exception("No access token in response")
              
              access_token = token_response["access_token"]
              print("✓ Token refreshed successfully")
              
              # Output for GitHub Actions
              if "GITHUB_OUTPUT" in os.environ:
                  with open(os.environ["GITHUB_OUTPUT"], "a") as f:
                      f.write(f"access_token={access_token}\n")
                      if "refresh_token" in token_response:
                          f.write(f"new_refresh_token={token_response['refresh_token']}\n")
              
              # Mask the token in logs
              print(f"::add-mask::{access_token}")
              
          except Exception as e:
              print(f"❌ Error: {str(e)}")
              exit(1)
          EOF

      # Update secrets using GitHub API if we have a new refresh token
      - name: Update GitHub Secrets
        if: steps.refresh_token.outputs.new_refresh_token
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const sodium = require('tweetsodium');
            
            // Get the public key for encrypting secrets
            const { data: publicKey } = await github.rest.actions.getRepoPublicKey({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            
            // Encrypt and update the refresh token
            const refreshTokenValue = '${{ steps.refresh_token.outputs.new_refresh_token }}';
            const refreshTokenBytes = Buffer.from(refreshTokenValue);
            const keyBytes = Buffer.from(publicKey.key, 'base64');
            const encryptedRefreshToken = Buffer.from(
              sodium.seal(refreshTokenBytes, keyBytes)
            ).toString('base64');
            
            await github.rest.actions.createOrUpdateRepoSecret({
              owner: context.repo.owner,
              repo: context.repo.repo,
              secret_name: 'CLAUDE_REFRESH_TOKEN',
              encrypted_value: encryptedRefreshToken,
              key_id: publicKey.key_id,
            });
            
            console.log('✓ Updated CLAUDE_REFRESH_TOKEN secret');

      # Only run Claude action if this was triggered by a comment
      - name: Run Claude Code Action
        if: github.event_name == 'issue_comment' || github.event_name == 'pull_request_review_comment'
        uses: nimishchaudhari/claude-code-action-max-sub@main
        with:
          use_oauth: true
          claude_access_token: ${{ steps.refresh_token.outputs.access_token }}
          anthropic_model: 'claude-opus-4-20250514'
          max_thinking_length: 20000

      # Log success for scheduled runs
      - name: Log Scheduled Refresh Success
        if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
        run: |
          echo "✅ Scheduled token refresh completed successfully"
          echo "Next refresh will occur at the next scheduled time"