name: Claude Code Assistant (Simple Token Refresh)

# This is a simplified version that refreshes the token on each run
# without updating GitHub secrets

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  claude-with-refresh:
    if: contains(github.event.comment.body, '@claude')
    runs-on: ubuntu-latest
    
    steps:
      - name: Refresh Token and Run Claude
        env:
          CLAUDE_REFRESH_TOKEN: ${{ secrets.CLAUDE_REFRESH_TOKEN }}
        run: |
          # Inline Python script to refresh token
          ACCESS_TOKEN=$(python3 -c "
          import json, urllib.request, os, sys
          
          refresh_token = os.environ.get('CLAUDE_REFRESH_TOKEN')
          if not refresh_token:
              print('Error: CLAUDE_REFRESH_TOKEN not set', file=sys.stderr)
              sys.exit(1)
          
          # Prepare request
          url = 'https://console.anthropic.com/v1/oauth/token'
          data = json.dumps({
              'grant_type': 'refresh_token',
              'refresh_token': refresh_token
          }).encode('utf-8')
          
          req = urllib.request.Request(url, data=data)
          req.add_header('Content-Type', 'application/json')
          
          try:
              with urllib.request.urlopen(req) as response:
                  result = json.loads(response.read().decode('utf-8'))
                  print(result.get('access_token', ''))
          except Exception as e:
              print(f'Error refreshing token: {e}', file=sys.stderr)
              sys.exit(1)
          ")
          
          if [ -z "$ACCESS_TOKEN" ]; then
            echo "Failed to refresh token"
            exit 1
          fi
          
          echo "::add-mask::$ACCESS_TOKEN"
          echo "CLAUDE_ACCESS_TOKEN=$ACCESS_TOKEN" >> $GITHUB_ENV

      - name: Run Claude Code Action
        uses: grll/claude-code-action@beta
        with:
          use_oauth: true
          claude_access_token: ${{ env.CLAUDE_ACCESS_TOKEN }}
          anthropic_model: 'claude-opus-4-20250514'
          max_thinking_length: 20000