name: Claude Code Assistant (API Key Authentication)

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  claude-api-key:
    # Only run if comment contains @claude
    if: contains(github.event.comment.body, '@claude')
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Run Claude Code Action with API Key
        uses: nimishchaudhari/claude-code-action-max-sub@main
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          anthropic_model: 'claude-opus-4-20250514'