name: Test OAuth Refresh

on:
  push:
    branches:
      - add-oauth-refresh-workflow

jobs:
  test-refresh:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Test refresh script exists and has correct syntax
        run: |
          echo "Testing refresh script..."
          node -c scripts/refresh-token.js
          echo "✅ Script syntax is valid"
      
      - name: Test workflow file
        run: |
          echo "Checking workflow file exists..."
          ls -la .github/workflows/refresh-oauth-token.yml
          echo "✅ Workflow file exists"